{ config, pkgs, inputs, ... }:

let
  # Track whatever programs.hyprland resolved to rather than re-deriving the
  # package from inputs. This session is the one that actually runs day to
  # day, so a compositor patch applied over in ./hyprland.nix (e.g. the
  # interlaced-modeline fix) has to reach it too — pinning to the raw flake
  # input here would have silently left this session on stock Hyprland while
  # the unused normal session got the patched build.
  hyprlandPkg = config.programs.hyprland.package;

  # Launches a *separate* Hyprland instance with the hand-written Hyprlain Lua
  # config (see home/modules/desktop/hyprlain.nix). This is distinct from the
  # normal session, whose config is generated by home-manager.
  #
  # Mirror the normal session's launch (uwsm start -D Hyprland -> start-hyprland):
  # uwsm gives the systemd-managed session lifecycle, and start-hyprland is
  # Hyprland's own watchdog launcher. Launching Hyprland *directly* (bypassing
  # start-hyprland) is what triggered the "Hyprland is being launched without
  # start-hyprland" warning every session. start-hyprland passes everything after
  # `--` to Hyprland, so our custom -c config still applies.
  wrapper = pkgs.writeShellScriptBin "hyprland-hyprlain" ''
    exec ${pkgs.uwsm}/bin/uwsm start -N Hyprlain -D Hyprland -- \
      ${hyprlandPkg}/bin/start-hyprland -- -c "$HOME/.config/hypr-hyprlain/hyprland.lua"
  '';

  # A session package exposing share/wayland-sessions/hyprlain.desktop so the
  # display manager (SDDM) lists it alongside the normal Hyprland session.
  sessionPkg = pkgs.runCommand "hyprlain-session"
    { passthru.providedSessions = [ "hyprlain" ]; } ''
    mkdir -p $out/share/wayland-sessions
    cat > $out/share/wayland-sessions/hyprlain.desktop <<EOF
    [Desktop Entry]
    Name=Hyprland (Hyprlain)
    Comment=Hyprland compositor with the Hyprlain theme
    Exec=${wrapper}/bin/hyprland-hyprlain
    Type=Application
    EOF
  '';
in
{
  environment.systemPackages = [ wrapper ];

  # Register the Hyprlain session with the display manager so it appears in the
  # SDDM session picker (this is the primary fallback path: pick the normal
  # session if Hyprlain misbehaves).
  services.displayManager.sessionPackages = [ sessionPkg ];
}
